/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'harpa09' at '10/23/16 9:08 PM' with Gradle 3.1
 *
 * @author harpa09, @date 10/23/16 9:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
